# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -covermode atomic -coverprofile=profile.cov ./...

      - name: Send to Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          ignore: "cmd/log-milter/main.go,cmd/log-milter/milter.go,cmd/milter-check/main.go"

      - name: Install Postfix
        run: sudo -n -- apt-get update -q && sudo -n -- apt-get install -y postfix sasl2-bin libsasl2-2 libsasl2-modules ssl-cert cpio courier-authlib

      - name: Integration Test
        run: cd integration && SKIP_POSTFIX_AUTH=1 go run github.com/d--j/go-milter/integration/runner ./tests
